/*
// This is a comment.

// This file is generated by go generate.

package main

import (
    "fmt"
    "os"
)

func main() {
    // Read input from standard input.
    // Output to standard output.
    fmt.Println("Hello, World!")
    fmt.Println("This is a test of the function system!")
}
